/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Salpicadero.SalpicaderoObjetivo;
import Monitorizacion.GestorMonitores;
import java.awt.Color;

/**
 *
 * @author juanfrandm98
 */
public class PanelMonitorizacion extends javax.swing.JFrame {

    /**
     * Creates new form PanelMonitorizacion
     */
    public PanelMonitorizacion() {
        initComponents();
        ta = tf = tg = tc = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqTitulo = new javax.swing.JLabel();
        etiqTitulo3 = new javax.swing.JLabel();
        etiqTitulo1 = new javax.swing.JLabel();
        botonAceite = new javax.swing.JButton();
        botonGeneral = new javax.swing.JButton();
        botonFrenos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiqAceite = new javax.swing.JLabel();
        etiqFrenos = new javax.swing.JLabel();
        etiqGeneral = new javax.swing.JLabel();
        etiqTitulo2 = new javax.swing.JLabel();
        botonRepostar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        etiqGasolina = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        revAceite = new javax.swing.JLabel();
        revFrenos = new javax.swing.JLabel();
        revGeneral = new javax.swing.JLabel();
        revCombustible = new javax.swing.JLabel();
        tAceite = new javax.swing.JLabel();
        tFrenos = new javax.swing.JLabel();
        tGeneral = new javax.swing.JLabel();
        tCombustible = new javax.swing.JLabel();

        etiqTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        etiqTitulo.setText("Salpicadero");

        etiqTitulo3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        etiqTitulo3.setText("Revisiones");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqTitulo1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        etiqTitulo1.setText("Revisiones");

        botonAceite.setText("Revisar");
        botonAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceiteActionPerformed(evt);
            }
        });

        botonGeneral.setText("Revisar");
        botonGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneralActionPerformed(evt);
            }
        });

        botonFrenos.setText("Revisar");
        botonFrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrenosActionPerformed(evt);
            }
        });

        jLabel1.setText("Aceite:");

        jLabel2.setText("Frenos:");

        jLabel3.setText("General:");

        etiqAceite.setText("OK");

        etiqFrenos.setText("OK");

        etiqGeneral.setText("OK");

        etiqTitulo2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        etiqTitulo2.setText("Combustible");

        botonRepostar.setText("Repostar");
        botonRepostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRepostarActionPerformed(evt);
            }
        });

        jLabel4.setText("Combustible:");

        etiqGasolina.setText("100%");

        jLabel5.setText("Revoluciones");

        jLabel6.setText("Tiempo");

        jLabel7.setText("Aceite");

        jLabel8.setText("Frenos");

        jLabel9.setText("General");

        jLabel10.setText("Combust.");

        revAceite.setText("jLabel11");

        revFrenos.setText("jLabel11");

        revGeneral.setText("jLabel11");

        revCombustible.setText("jLabel11");

        tAceite.setText("jLabel11");

        tFrenos.setText("jLabel11");

        tGeneral.setText("jLabel11");

        tCombustible.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(revFrenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFrenos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(revAceite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tAceite))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(revCombustible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tCombustible))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(revGeneral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tGeneral)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(revAceite)
                    .addComponent(tAceite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(revFrenos)
                    .addComponent(tFrenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(revGeneral)
                    .addComponent(tGeneral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(revCombustible)
                    .addComponent(tCombustible))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonFrenos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqFrenos)
                            .addComponent(etiqGeneral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqAceite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(etiqTitulo2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonRepostar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiqGasolina)))
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(etiqTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqTitulo1)
                    .addComponent(etiqTitulo2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceite, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(etiqAceite)
                    .addComponent(botonRepostar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(etiqGasolina))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonFrenos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(etiqFrenos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(etiqGeneral)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceiteActionPerformed
        salpicadero.revisarAceite();
        ta = 0;
    }//GEN-LAST:event_botonAceiteActionPerformed

    private void botonGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneralActionPerformed
        salpicadero.revisarGeneral();
        tg = 0;
    }//GEN-LAST:event_botonGeneralActionPerformed

    private void botonFrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrenosActionPerformed
        salpicadero.revisarFrenos();
        tf = 0;
    }//GEN-LAST:event_botonFrenosActionPerformed

    private void botonRepostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRepostarActionPerformed
        gestor.repostar();
        tc = 0;
    }//GEN-LAST:event_botonRepostarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMonitorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMonitorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMonitorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMonitorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelMonitorizacion panel = new PanelMonitorizacion();
                 panel.setLocation(1000,400);
               // panel.setVisible(true);
               
            }
        });
    }
    
    public void setSalpicadero( SalpicaderoObjetivo salpicadero ) {
        this.salpicadero = salpicadero;
    }
    
    public void setGestor( GestorMonitores gestor ) {
        this.gestor = gestor;
    }
    
    public void setCapacidadGasolina( double capacidadGasolina ) {
        this.capacidadGasolina = capacidadGasolina;
    }
    
    public void comprobarPosibilidadRevision( boolean motorApagado ) {
        
        if( motorApagado == true && rpm == 0.0 )
            activarBotones( true );
        else
            activarBotones( false );
        
    }
        
    private void activarBotones( boolean estado ) {
        botonAceite.setEnabled( estado );
        botonFrenos.setEnabled( estado );
        botonGeneral.setEnabled( estado );
        botonRepostar.setEnabled( estado );
    }
    
    private void calcularTiempo( String componente ) {
        
        javax.swing.JLabel etiqueta = new javax.swing.JLabel();
        int tiempo = 0;
        String unidad = "s";
        
        switch( componente ) {
            case "ACEITE":
                ta += 0.1;
                tiempo = (int)ta;
                etiqueta = tAceite;
                break;
            case "FRENOS":
                tf += 0.1;
                tiempo = (int)tf;
                etiqueta = tFrenos;
                break;
            case "GENERAL":
                tg += 0.1;
                tiempo = (int)tg;
                etiqueta = tGeneral;
                break;
            case "COMBUSTIBLE":
                tc += 0.1;
                tiempo = (int)tc;
                etiqueta = tCombustible;
                break;
        }
        
        if( tiempo >= 60 ) {
            tiempo /= 60;
            unidad = "min";
        }
        
        etiqueta.setText( tiempo + unidad );
        
    }
    
    public void comprobarAceite( boolean necesita, double revolucionesAcumuladas ) {
        
        if( necesita ) {
            etiqAceite.setText( "Revisión necesaria" );
            etiqAceite.setForeground( Color.red );
        } else {
            etiqAceite.setText( "OK" );
            etiqAceite.setForeground( Color.green );
        }
        
        revAceite.setText( String.format( "%.2f", revolucionesAcumuladas ) );
        calcularTiempo( "ACEITE" );
        
    }
    
    public void comprobarFrenos( boolean necesita, double revolucionesAcumuladas ) {
        
        if( necesita ) {
            etiqFrenos.setText( "Revisión necesaria" );
            etiqFrenos.setForeground( Color.red );
        } else {
            etiqFrenos.setText( "OK" );
            etiqFrenos.setForeground( Color.green );
        }
        
        revFrenos.setText( String.format( "%.2f", revolucionesAcumuladas ) );
        calcularTiempo( "FRENOS" );
        
    }
    
    public void comprobarGeneral( boolean necesita, double revolucionesAcumuladas ) {
        
        if( necesita ) {
            etiqGeneral.setText( "Revisión necesaria" );
            etiqGeneral.setForeground( Color.red );
        } else {
            etiqGeneral.setText( "OK" );
            etiqGeneral.setForeground(Color.green );
        }
        
        revGeneral.setText( String.format( "%.2f", revolucionesAcumuladas ) );
        calcularTiempo( "GENERAL" );
        
    }
    
    public void actualizarRevoluciones( double rpm ) {
        this.rpm = rpm;
    }
    
    public void actualizarGasolina( double cantidadGasolina, double revolucionesAcumuladas ) {
        
        int porcentaje = (int) ( cantidadGasolina * 100 / capacidadGasolina );
        
        etiqGasolina.setText( Integer.toString( porcentaje ) + "%" );
        colorGasolina( porcentaje );
        
        revCombustible.setText( String.format( "%.2f", revolucionesAcumuladas ) );
        calcularTiempo( "COMBUSTIBLE" );
        
    }
    
    public void colorGasolina( int porcentaje ) {
        
        if( porcentaje >= 50 )
            etiqGasolina.setForeground( Color.green );
        else if( porcentaje >= 25 && porcentaje < 50 )
            etiqGasolina.setForeground( Color.yellow );
        else if( porcentaje >= 10 && porcentaje < 25 )
            etiqGasolina.setForeground( Color.orange );
        else
            etiqGasolina.setForeground( Color.red );
        
    }
    
    // Salpicadero
    SalpicaderoObjetivo salpicadero;
    GestorMonitores gestor;
    private double rpm = 0.0;
    private double capacidadGasolina;
    
    // Tiempos monitorización
    double ta, tf, tg, tc;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceite;
    private javax.swing.JButton botonFrenos;
    private javax.swing.JButton botonGeneral;
    private javax.swing.JButton botonRepostar;
    private javax.swing.JLabel etiqAceite;
    private javax.swing.JLabel etiqFrenos;
    private javax.swing.JLabel etiqGasolina;
    private javax.swing.JLabel etiqGeneral;
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JLabel etiqTitulo1;
    private javax.swing.JLabel etiqTitulo2;
    private javax.swing.JLabel etiqTitulo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel revAceite;
    private javax.swing.JLabel revCombustible;
    private javax.swing.JLabel revFrenos;
    private javax.swing.JLabel revGeneral;
    private javax.swing.JLabel tAceite;
    private javax.swing.JLabel tCombustible;
    private javax.swing.JLabel tFrenos;
    private javax.swing.JLabel tGeneral;
    // End of variables declaration//GEN-END:variables
}
