/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patronobservador;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author juanfrandm98
 */
public class GraficaTemperatura extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form GraficaTemperatura
     */
    public GraficaTemperatura() {
        initComponents();
        inicializarVectores();
        this.setLocation(334, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valor0 = new javax.swing.JLabel();
        grafica0 = new javax.swing.JLabel();
        valor1 = new javax.swing.JLabel();
        grafica1 = new javax.swing.JLabel();
        valor2 = new javax.swing.JLabel();
        valor3 = new javax.swing.JLabel();
        valor4 = new javax.swing.JLabel();
        valor5 = new javax.swing.JLabel();
        valor6 = new javax.swing.JLabel();
        valor7 = new javax.swing.JLabel();
        valor8 = new javax.swing.JLabel();
        valor9 = new javax.swing.JLabel();
        grafica2 = new javax.swing.JLabel();
        grafica3 = new javax.swing.JLabel();
        grafica4 = new javax.swing.JLabel();
        grafica5 = new javax.swing.JLabel();
        grafica6 = new javax.swing.JLabel();
        grafica7 = new javax.swing.JLabel();
        grafica8 = new javax.swing.JLabel();
        grafica9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Gráfica Temperatura");

        valor0.setText(" ");

        grafica0.setText(" ");

        valor1.setText(" ");

        grafica1.setText(" ");

        valor2.setText(" ");

        valor3.setText(" ");

        valor4.setText(" ");

        valor5.setText(" ");

        valor6.setText(" ");

        valor7.setText(" ");

        valor8.setText(" ");

        valor9.setText(" ");

        grafica2.setText(" ");

        grafica3.setText(" ");

        grafica4.setText(" ");

        grafica5.setText(" ");

        grafica6.setText(" ");

        grafica7.setText(" ");

        grafica8.setText(" ");

        grafica9.setText(" ");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N
        jLabel2.setText("-50ºC");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N
        jLabel3.setText("100ºC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valor8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(grafica8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(valor0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel3))
                                .addComponent(grafica0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valor9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grafica9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor0)
                    .addComponent(grafica0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor1)
                    .addComponent(grafica1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor2)
                    .addComponent(grafica2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor3)
                    .addComponent(grafica3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor4)
                    .addComponent(grafica4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor5)
                    .addComponent(grafica5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor6)
                    .addComponent(grafica6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor7)
                    .addComponent(grafica7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grafica8)
                    .addComponent(valor8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grafica9)
                    .addComponent(valor9))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaTemperatura().setVisible(true);
                
            }
        });
    }
    
    private void inicializarVectores() {
        
        graficas = new ArrayList();
        
        graficas.add( grafica0 );
        graficas.add( grafica1 );
        graficas.add( grafica2 );
        graficas.add( grafica3 );
        graficas.add( grafica4 );
        graficas.add( grafica5 );
        graficas.add( grafica6 );
        graficas.add( grafica7 );
        graficas.add( grafica8 );
        graficas.add( grafica9 );
        
        valores = new ArrayList();
        
        valores.add( valor0 );
        valores.add( valor1 );
        valores.add( valor2 );
        valores.add( valor3 );
        valores.add( valor4 );
        valores.add( valor5 );
        valores.add( valor6 );
        valores.add( valor7 );
        valores.add( valor8 );
        valores.add( valor9 );
        
        temperaturas = new ArrayList();
        asteriscos = new ArrayList();
        
    }
    
    private ArrayList<javax.swing.JLabel> graficas;
    private ArrayList<javax.swing.JLabel> valores;
    private ArrayList<String> temperaturas;
    private ArrayList<String> asteriscos;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grafica0;
    private javax.swing.JLabel grafica1;
    private javax.swing.JLabel grafica2;
    private javax.swing.JLabel grafica3;
    private javax.swing.JLabel grafica4;
    private javax.swing.JLabel grafica5;
    private javax.swing.JLabel grafica6;
    private javax.swing.JLabel grafica7;
    private javax.swing.JLabel grafica8;
    private javax.swing.JLabel grafica9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valor0;
    private javax.swing.JLabel valor1;
    private javax.swing.JLabel valor2;
    private javax.swing.JLabel valor3;
    private javax.swing.JLabel valor4;
    private javax.swing.JLabel valor5;
    private javax.swing.JLabel valor6;
    private javax.swing.JLabel valor7;
    private javax.swing.JLabel valor8;
    private javax.swing.JLabel valor9;
    // End of variables declaration//GEN-END:variables

    private String calcularAsteriscos( float temperatura ) {
        
        if( temperatura <= -40 )
            return "*";
        else if( temperatura > -40 && temperatura <= -30 )
            return "**";
        else if( temperatura > -30 && temperatura <= -20 )
            return "***";
        else if( temperatura > -20 && temperatura <= -10 )
            return "****";
        else if( temperatura > -10 && temperatura <= 0 )
            return "*****";
        else if( temperatura > 0 && temperatura <= 10 )
            return "******";
        else if( temperatura > 10 && temperatura <= 20 )
            return "*******";
        else if( temperatura > 20 && temperatura <= 30 )
            return "********";
        else if( temperatura > 30 && temperatura <= 40 )
            return "*********";
        else if( temperatura > 40 && temperatura <= 50 )
            return "**********";
        else if( temperatura > 50 && temperatura <= 60 )
            return "***********";
        else if( temperatura > 60 && temperatura <= 70 )
            return "************";
        else if( temperatura > 70 && temperatura <= 80 )
            return "*************";
        else if( temperatura > 80 && temperatura <= 90 )
            return "**************";
        else
            return "***************";

    }
    
    private void actualizarEtiquetas() {
        
        for( int i = 0; i < temperaturas.size(); i++ ) {
            valores.get(i).setText( temperaturas.get(i) );
            graficas.get(i).setText( asteriscos.get(i) );
        }
        
    }
    
    @Override
    public void update(Observable o, Object arg) {
        
        float temperatura = Float.parseFloat( arg.toString() );
        
        if( temperaturas.size() > 9 ) {
            temperaturas.remove(0);
            asteriscos.remove(0);
        }
        
        temperaturas.add( arg.toString() );
        asteriscos.add( calcularAsteriscos( temperatura ) );
        
        actualizarEtiquetas();
    }
}
